// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qayxeeuojrmhwrevyapn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFheXhlZXVvanJtaHdyZXZ5YXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODQwMjYsImV4cCI6MjA2MTM2MDAyNn0.l1T7rv59S5uTaqpsk-6aXgjts_c8F6u7sAT27jwjTfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);